add cgif
wchaws/serverless-image-handler pull request #134
Opened 2022-07-21 09:44 UTC by adonismile

**Issue #, if available:**

https://github.com/wchaws/serverless-image-handler/issues/133#issue-1312427986

**Description of changes:**

Added Gif frame capture function, return input frame number Gif.
Deploy Fargate in configured private subnets.
Add the enable and disable of CloudFront.
Add internal and internet options for ALB.

**Checklist**
- [ ] :wave: I have run the unit tests, and all unit tests have passed.
- [ ] :warning: This pull request might incur a breaking change.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-07-22 03:40 UTC, adonismile commented
add some comments in cdk.context.json

2022-07-25 07:16 UTC, wchaws requested changes
还漏了单元测试

2022-07-25 07:16 UTC, wchaws commented on source/constructs/README.md
> +| subnet_ids    | 部署程序或者内部ALB的子网，同一AZ下仅可配置一个（可选）|
建议英文跟中文通过空格分开。例如：部署程序或者内部 ALB 的子网，同一 AZ 下仅可配置一个（可选）

2022-07-25 07:16 UTC, wchaws commented on source/constructs/lib/ecs-image-handler.ts
> +  if (publicLoadBalancer === false) {
```
if (!publicLoadBalancer)
```

2022-07-25 07:16 UTC, wchaws commented on source/constructs/lib/ecs-image-handler.ts
> +  if (enableCloudFront === false) {
if (!enableCloudFront) {

2022-07-25 07:16 UTC, wchaws commented on source/new-image-handler/src/processor/image/cgif.ts
> +export class CgitAction extends BaseImageAction {
拼写错误：Cgif 不是 Cgit

2022-07-25 07:16 UTC, wchaws commented on source/new-image-handler/src/processor/image/index.ts
> +import { CgitAction } from './cgif';
拼写错误

2022-07-25 07:16 UTC, wchaws commented on source/new-image-handler/src/processor/image/index.ts
> +  new CgitAction(),
拼写错误

2022-07-25 07:16 UTC, wchaws commented on source/new-image-handler/src/processor/image/index.ts
> +      }
建议把这一坨挪到 CgitAction 的 beforeNewContext 里面，就差一步了。

2022-07-25 07:16 UTC, wchaws commented on source/new-image-handler/src/processor/image/index.ts
> +    if (cgifFramesNum > 0) {
可以通过增加一个 ctx.features 来拿到这个值

2022-07-25 07:16 UTC, wchaws commented on source/new-image-handler/src/processor/image/index.ts
> +        cgifFramesNum = metadata.pages;
一个小技巧去限制值的范围
```
cgifFramesNum = Math.min(cgifFramesNum, metadata.pages)
```

2022-07-26 06:47 UTC, adonismile commented on source/constructs/README.md
> +| subnet_ids    | 部署程序或者内部ALB的子网，同一AZ下仅可配置一个（可选）|
已经按照格式修改。

2022-07-26 06:49 UTC, adonismile commented on source/constructs/lib/ecs-image-handler.ts
> +  if (publicLoadBalancer === false) {
当配置中enable_public_alb为空的时候和配置为true的时候按照原逻辑处理。仅当为false的时候走之后的逻辑。

2022-07-26 06:49 UTC, adonismile commented on source/constructs/lib/ecs-image-handler.ts
> +  if (enableCloudFront === false) {
当配置中enable_public_alb为空的时候和配置为true的时候按照原逻辑处理。仅当为false的时候走之后的逻辑。

2022-07-26 06:50 UTC, adonismile commented on source/new-image-handler/src/processor/image/index.ts
> +import { CgitAction } from './cgif';
已修改

2022-07-26 06:50 UTC, adonismile commented on source/new-image-handler/src/processor/image/index.ts
> +  new CgitAction(),
已经修改

2022-07-26 06:51 UTC, adonismile commented on source/new-image-handler/src/processor/image/index.ts
> +      }
已经放到了CgifAction。

2022-07-26 06:51 UTC, adonismile commented on source/new-image-handler/src/processor/image/index.ts
> +    if (cgifFramesNum > 0) {
按照这个方式修改。

2022-07-26 06:52 UTC, adonismile commented on source/new-image-handler/src/processor/image/index.ts
> +        cgifFramesNum = metadata.pages;
已经修改，并且增加了单元测试

2022-07-26 06:52 UTC, adonismile commented
已经按照comments进行修改。

2022-07-26 07:16 UTC, wchaws requested changes

2022-07-26 07:16 UTC, wchaws commented on source/new-image-handler/test/processor/index.test.ts
> +  const ctx = await ImageProcessor.getInstance().newContext('example.gif', 'image/cgif,s_2'.split('/'), fixtureStore);
再加一个 cgif,s_100 越界的 case

2022-07-26 07:21 UTC, wchaws commented on source/constructs/lib/ecs-image-handler.ts
> +  if (publicLoadBalancer === false) {
ok，我搞错了

2022-07-26 07:40 UTC, adonismile commented on source/new-image-handler/test/processor/index.test.ts
> +  const ctx = await ImageProcessor.getInstance().newContext('example.gif', 'image/cgif,s_2'.split('/'), fixtureStore);
已经添加

2022-07-26 08:46 UTC, wchaws approved these changes

2022-07-26 08:46 UTC, merged