Cdn parameter spec adapt
wchaws/serverless-image-handler pull request #165
Opened 2023-06-20 09:22 UTC by twu-AWS

**Issue #, if available:**

https://github.com/wchaws/serverless-image-handler/issues/162

**Description of changes:**

**Checklist**
- [ ] :wave: I have run the unit tests, and all unit tests have passed.
- [ ] :warning: This pull request might incur a breaking change.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-06-20 09:56 UTC, wchaws requested changes

2023-06-20 09:56 UTC, wchaws commented on source/new-image-handler/src/default.ts
> +  ['alicdnimage']: ImageProcessor.getInstance(),
请删除 alicdn

2023-06-20 09:56 UTC, wchaws commented on source/new-image-handler/src/processor/image/index.ts
> +    //   : (isAliCdnImage = false);
请删除注释代码

2023-06-20 09:56 UTC, wchaws commented on source/new-image-handler/src/processor/image/index.ts
> +      //  : (actionname = params[0]);
删除注释代码

2023-06-20 09:56 UTC, wchaws commented on source/new-image-handler/src/processor/image/index.ts
> +  needHandle?: boolean;
这个字短看上去是不需要了

2023-06-20 09:56 UTC, wchaws commented on .vscode/settings.json
这个文件能 rollback 么？

2023-06-20 09:56 UTC, wchaws commented on source/constructs/package.json
这个文件能 rollback 么？目前这个项目的 cdk 版本是锁死的。暂时不升级，所以不需要用 npx 去拿最新的 cdk

2023-06-20 09:56 UTC, wchaws commented on source/new-image-handler/.eslintrc.json
这个 可以 rollback 么？

2023-06-20 09:56 UTC, wchaws commented on source/new-image-handler/src/processor/image/index.ts
> +    }
这段代码看上去暂时不需要了

2023-06-20 09:56 UTC, wchaws commented on source/new-image-handler/src/processor/image/index.ts
> +      console.log(`initial params is ${params}`);
这个调试过程中的 log 可以去掉么？

2023-06-20 09:56 UTC, wchaws commented on source/new-image-handler/src/processor/image/index.ts
> +      needHandle: isHandle,
这段代码看上去暂时不需要了

2023-06-20 10:04 UTC, twu-AWS commented on source/constructs/package.json
但是对于很多本地全局安装了 cdk 的客户来说它会overwrite 你本地的设置啊。所以用npx 指定当前项目的版本才是make sense 的吧？

2023-06-21 01:53 UTC, wchaws commented on source/constructs/package.json
不会，它只会 overwrite 当前目录下的 cdk。你全局安装的 cdk 不影响。

2023-06-25 08:18 UTC, merged